---
    - name: Create a Virtual Network

      azure.azcollection.azure_rm_virtualnetwork:

        subscription_id: "{{ subscription_id }}"

        tenant: "{{ tenant }}"

        client_id: "{{ client_id }}"

        secret: "{{ secret }}"

        resource_group: "{{ rg_name }}"

        name: "{{ vnet_name }}"

        address_prefixes: "10.0.0.0/16"

      register: vnet