- name: Create an Storage Account

  azure_rm_storageaccount:
    
        subscription_id: "{{ subscription_id }}"

        tenant: "{{ tenant }}"

        client_id: "{{ client_id }}"

        secret: "{{ secret }}"

        resource_group: "{{ rg_name }}"
    
        name: "{{ storage_account_name }}"
    
        type: "{{ storage_type }}"