---

- name: Create a Virtual Network Interface Card

  azure.azcollection.azure_rm_networkinterface:

        subscription_id: "{{ subscription_id }}"

        tenant: "{{ tenant }}"

        client_id: "{{ client_id }}"

        secret: "{{ secret }}"

        resource_group: "{{ rg_name }}"

        name: "{{ vm_name }}-nic"

        virtual_network: "{{ vnet_name }}"

        subnet_name: "{{ subnet_name }}"

        ip_configurations:
          - name: "{{ vm_name }}-config_ip"
            public_ip_address_name: "{{ vm_name }}-public-ip"
            primary: true

        #public_ip_address_name: "{{ vm_name }}-public-ip"

        security_group: "{{ vm_name }}-nsg"