---
    - name: Create a Virtual Machine

      azure.azcollection.azure_rm_virtualmachine:

        subscription_id: "{{ subscription_id }}"

        tenant: "{{ tenant }}"

        client_id: "{{ client_id }}"

        secret: "{{ secret }}"

        resource_group: "{{ rg_name }}"

        name: "{{ vm_name }}"

        vm_size: "{{ vm_size }}"

        admin_username: "{{ admin_username }}"

        admin_password: "{{ admin_password }}"

        image: 

          offer: "RHEL"

          publisher: "redhat"

          sku: "8-LVM"

          version: "latest"
        
        storage_account_name: "{{storage_account_name}}"

        os_disk_caching: ReadWrite

        os_disk_name: "{{ vm_name }}-os-disk"

        #network_interface_names:

        #  - "{{ vm_name }}-nic"

        network_interfaces:

          - name: "{{ vm_name }}-nic"

            properties:

              primary: True
        ssh_password_enabled: false
        ssh_public_keys: 
          - path: /home/{{admin_username}}/.ssh/authorized_keys
            key_data: "{{ssh_pub}}"