---
- name: Obter info das VMs em todos os grupos de recursos na Azure
  hosts: localhost
  gather_facts: false
  vars:
    subscription_id: 8ab000c0-31b3-4536-ada7-95518604d788

    tenant: dcb51ddf-8169-474d-92da-ee67c281623c

    client_id: 07903319-362a-4af8-81d1-73889ccd97e5

    secret: YMj8Q~~7w5WX4yYldaLTkRAooiSzR5xQmFcU_bkH

  tasks:

    - name: Obter facts dos resource groups na Azure
      azure.azcollection.azure_rm_resourcegroup_info:
        subscription_id: "{{ subscription_id }}"

        tenant: "{{ tenant }}"

        client_id: "{{ client_id }}"

        secret: "{{ secret }}"

        list_resources: true

      register: resource_groups
      
    - name: Obtendo os nomes de cada resource group em uma lista
      ansible.builtin.set_fact:
        rg_names: "{{ resource_groups.resourcegroups | map(attribute='name') | list }}"

    - name: Obter facts dos resource groups na Azure
      azure.azcollection.azure_rm_virtualmachine_info:
        subscription_id: "{{ subscription_id }}"

        tenant: "{{ tenant }}"

        client_id: "{{ client_id }}"

        secret: "{{ secret }}"

        resource_group: "{{ item }}"

      register: vms_info
      loop: "{{ rg_names }}"
      #when: item is search('redhat_brasil') #provisiorio durante os testes
    - debug:
        msg: "{{vms_info}}"

  
      
      
       
      

      
  
    
     

   # - name: Get VMs in Resource groups
   #   azure.azcollection.azure_rm_virtualmachine_info:
   #     subscription_id: "{{ subscription_id }}"

   #     tenant: "{{ tenant }}"

   #     client_id: "{{ client_id }}"

   #     secret: "{{ secret }}"

   #     resource_group: "{{ item.name }}"

    



 

   # - name: Iterar sobre os resource groups
   #   set_fact:
   #     rg_names: "{{ resource_groups['resourcegroups'] | map(attribute='name')| list }}"
      

    
 
   

    

    #- name: Obter facts das VMs na Azure por rg_name
    #  azure.azcollection.azure_rm_virtualmachine_info:
    #    resource_group: "{{ item }}"
    #  loop: "{{rg_names}}"
    #  register: vm_facts
#
    #- name: teste de variavel
    # debug:
    #    msg: "{{vm_facts}}"
    #  loop: "{{vm_facts}}"

    #    - name: Add infos ao relatorio
    #      set_fact:
    #        report_content: "{{ report_content }}\n\nRelatorio de VMs da Azure\nResource Group - {{ item }}:\n\n{%for vm in vm_facts.virtualmachiones %} - Nome da VM: {{ vm.name }}\n Última Reinicialização: {{ vm.instance_view.statuses[-1].time }}\n{% endfor %}"
    #      loop: "{{ rg_names }}"
        

    
      